from turtle import *

def house():
    color("black","saddle brown")
    pensize(5)

    penup()
    goto(-200,-200)
    pendown()
    y = -200
    begin_fill()
    for i in range(2):
        forward(500)
        left(90)
        forward(300)
        left(90)
    end_fill()
    for i in range(5):
        begin_fill()
        circle(30)
        end_fill()
        penup()
        y += 60
        goto(-200,y)
        pendown()

    penup()
    y -= 60
    goto(300,y)
    pendown()
    for i in range(5):
        begin_fill()
        circle(30)
        end_fill()
        penup()
        y -= 60
        goto(300,y)
        pendown()
    y += 60
    penup()
    goto(300,y)
    pendown()
    left(180)
    forward(500)

    right(90)
    penup()
    forward(300)
    pendown()
    right(90)
    forward(180)
    right(90)
    pensize(15)
    color("black", "sienna")
    begin_fill()
    forward(300)
    left(90)
    forward(140)
    left(90)
    forward(300)
    left(90)
    forward(140)
    end_fill()

    penup()
    goto(-200,100)
    pendown()
    color("black","tan")
    pensize(5)
    begin_fill()
    forward(60)
    right(150)
    forward(350)
    right(60)
    forward(350)
    right(150)
    forward(60)
    end_fill()

    penup()
    goto(50,225)
    pendown()

    color("black","DeepSkyBlue")
    begin_fill()
    circle(50)
    end_fill()
    left(90)
    forward(100)
    left(180)
    forward(50)
    left(90)
    forward(50)
    right(180)
    forward(100)

# house()
# hideturtle()
# exitonclick()